name: Test Excubitor-Backend

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.19', '1.20']

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install PAM dependency
        run: sudo apt install -y libpam0g-dev

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build
        run: make build

      - name: Test
        run: make test
